services:
  api:
    image: elimuhub/api:8a79ff57250b6b641a35b2b346e5eb5b7b3ae600
    depends_on:
      - minio
    ports:
      - "8000:8000"
    env_file:
      - .env.production.api

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      .env.production.minio
    environment:
      - MINIO_ROOT_USER=minioadmin      
      - MINIO_ROOT_PASSWORD=minioadmin   
    command: server /data --console-address ":9001"
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'    
          memory: 512M   
        reservations:
          memory: 256M   # Guarantee at least 256MB RAM

volumes:
  minio_data: {}