import os

S3_LOCAL_ENDPOINT_URL = os.environ["S3_LOCAL_ENDPOINT_URL"]
BUCKET_NAME = os.environ["BUCKET_NAME"]
AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
AWS_REGION = os.environ["AWS_REGION"]
ENVIRONMENT = os.environ["ENVIRONMENT"]
PRESIGNED_URL_EXPIRATION = 604000
