"""generated

Revision ID: b8624c0ebfd6
Revises: afe4866bf5af
Create Date: 2024-12-16 02:09:49.883569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8624c0ebfd6'
down_revision: Union[str, None] = 'afe4866bf5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nemis_number', sa.String(), nullable=True))
    op.alter_column('students', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'grade_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('students', 'nemis_number')
    # ### end Alembic commands ###