services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # minio:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"  # API endpoint
  #     - "9001:9001"  # Console/GUI
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin      # Change these credentials
  #     - MINIO_ROOT_PASSWORD=minioadmin   # in production
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

