services:
  postgres_db:
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: dev_postgres
    environment:
      POSTGRES_DB: schoolsas
      POSTGRES_USER: schoolsas
      POSTGRES_PASSWORD: schoolsas
    ports:
      - "5433:5432"

  # minio:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"  # API endpoint
  #     - "9001:9001"  # Console/GUI
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin      # Change these credentials
  #     - MINIO_ROOT_PASSWORD=minioadmin   # in production
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
