services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: schoolsas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network



networks:
  app_network:
    driver: bridge

volumes:
  minio:
    driver: local

