services:
  api:
    image: elimuhub/api:latest
    pull_policy: always
    depends_on:
      - minio
    ports:
      - "8080:8080"
    env_file:
      - .env.production.api
  fronted:
    image: elimuhub/api:frontend-latest
    pull_policy: always
    ports:
      - "3000:3000"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      .env.production.minio

    command: server /data --console-address ":9001"
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      
volumes:
  minio_data: {}