---
- name: Setup API deployment
  hosts: localhost
  connection: local
  become: yes
  vars:
    deploy_user: api_deploy
    app_path: /opt/api
    
  tasks:
    - name: Create deployment user and add to docker group
      user:
        name: "{{ deploy_user }}"
        shell: /bin/bash
        system: yes
        create_home: yes
        groups: docker
        append: yes

    - name: Create SSH directory and generate key
      block:
        - name: Create SSH directory
          file:
            path: "/home/{{ deploy_user }}/.ssh"
            state: directory
            owner: "{{ deploy_user }}"
            group: "{{ deploy_user }}"
            mode: '0700'

        - name: Generate SSH key
          openssh_keypair:
            path: "/home/{{ deploy_user }}/.ssh/id_ed25519"
            type: ed25519
            owner: "{{ deploy_user }}"
            group: "{{ deploy_user }}"
            mode: '0600'

        - name: Setup authorized_keys
          copy:
            dest: "/home/{{ deploy_user }}/.ssh/authorized_keys"
            content: |
              command="cd {{ app_path }} && docker compose pull && docker compose up -d",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty {{ lookup('file', '/home/' + deploy_user + '/.ssh/id_ed25519.pub') }}
            owner: "{{ deploy_user }}"
            group: "{{ deploy_user }}"
            mode: '0600'

    - name: Setup application directory
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0755'

    - name: Save deployment information
      block:
        - name: Copy deployment key
          copy:
            src: "/home/{{ deploy_user }}/.ssh/id_ed25519"
            dest: "/home/setup-scripts/ansible/keys/api_deploy_key"
            mode: '0600'
            remote_src: yes

        - name: Generate and save known_hosts
          shell: "ssh-keyscan -H localhost > /home/setup-scripts/ansible/keys/known_hosts"